feat(cache): support multiple versions of symfony/cache
tebru/retrofit-php pull request #85
Opened 2020-02-20 19:18 UTC by Gounlaf

Create a CacheProvider to create the appropriate instance of cache depending on symfony cache version.
This is to support versions ^3.3|^4.0|^5.0 of symfony/cache (since 4.3, classes in Simple namespace are deprecated, and removed in 5.x)

2020-02-20 20:21 UTC, natebrunette commented
Part of this already got merged in, you might want to rebase.

2020-02-20 20:41 UTC, Gounlaf commented
> Part of this already got merged in, you might want to rebase.

Hi @natebrunette,

It's done on tebru/gson-php, not here.
I've implemented it here

2020-03-03 09:44 UTC, Gounlaf commented
Hi @natebrunette,

Can you take a look?
This update is necessary to use `tebru/retrofit-php` with `tebru/retrofit-php-converter-gson` / `tebru/gson-php` with symfony components 5.*

2020-03-05 18:54 UTC, natebrunette commented
@Gounlaf it looks like tests failed

2020-03-05 19:50 UTC, natebrunette requested changes
Could you just remove the lock file as well?

2020-03-05 19:50 UTC, natebrunette commented on src/Internal/CacheProvider.php
> +    public static function createFileCache(string $cacheDir): CacheInterface
docblock

2020-03-05 19:51 UTC, natebrunette commented
Once the issues are address and it's squashed I'll merge

2020-03-05 20:42 UTC, Gounlaf commented on src/Internal/CacheProvider.php
> +    public static function createFileCache(string $cacheDir): CacheInterface
fixed

2020-03-05 21:08 UTC, natebrunette commented
@Gounlaf shouldn't there be an update to gitignore too?

2020-03-06 09:35 UTC, Gounlaf commented
> @Gounlaf shouldn't there be an update to gitignore too?

Done; if it's okay I will squash again

2020-03-06 22:42 UTC, natebrunette commented
probably add a `/` to make it `composer.lock` to be safe, but yeah, that's fine.

2020-03-06 23:23 UTC, Gounlaf commented
> probably add a `/` to make it `/composer.lock` to be safe, but yeah, that's fine.

fixed & squashed

2020-03-07 00:40 UTC, merged

2020-03-12 13:10 UTC, Gounlaf commented
Hi @natebrunette,

Since it's merged, can you please make a release?

Thanks,
Regards.

2020-03-12 14:52 UTC, natebrunette commented
I tagged new releases of gson and retrofit